"""id de criador tabela convenios

Revision ID: 5a9b42dc731b
Revises: 5f05786aad95
Create Date: 2025-10-27 14:48:25.625693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a9b42dc731b'
down_revision = '5f05786aad95'
branch_labels = None
depends_on = None


def upgrade():
    # --- INÍCIO DA CORREÇÃO MANUAL PARA NOT NULL VIOLATION ---

    # 1. Adiciona a coluna 'user_id' permitindo NULLs TEMPORARIAMENTE
    with op.batch_alter_table('convenio', schema=None) as batch_op:
        # Note: Mudamos nullable para True
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    # 2. CRUCIAL: Preenche todas as linhas existentes com o user_id '2'.
    # *** IMPORTANTE: Garanta que o usuário com id=2 exista no seu banco de dados! ***
    op.execute("UPDATE convenio SET user_id = 2 WHERE user_id IS NULL")

    # 3. Altera a coluna para ser NOT NULL e adiciona a Chave Estrangeira
    with op.batch_alter_table('convenio', schema=None) as batch_op:
        # Altera a coluna para NOT NULL
        batch_op.alter_column('user_id',
                              existing_type=sa.Integer(),
                              nullable=False)

        # Adiciona a chave estrangeira (FK)
        # O None é o nome automático que o Alembic usaria.
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # --- FIM DA CORREÇÃO MANUAL ---


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('convenio', schema=None) as batch_op:
        # A ordem para o downgrade é: 1. Drop FK; 2. Drop Column
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###
