"""Alterando tipo da coluna record_id para String na tabela audit_log

Revision ID: 5f05786aad95
Revises: cda769ccc980
Create Date: 2025-09-26 13:12:20.136283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f05786aad95'
down_revision = 'cda769ccc980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.alter_column('record_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.alter_column('record_id',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###
