"""Colunas adicionadas: string, int, date, text e enum e outras modificações

Revision ID: 81e5e3142890
Revises: 
Create Date: 2025-09-18 14:25:25.185515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81e5e3142890'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('convenio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnpj', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('nome_fantasia', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('estado', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('area_atuacao', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('qtd_funcionarios', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('qtd_associados', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('qtd_sindicalizados', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('responsavel_legal', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('cargo_responsavel', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('email_responsavel', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('telefone_responsavel', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('diretor_responsavel', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('data_assinatura', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('observacoes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('caminho_arquivo_pdf', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Enum('ativo', 'rescindido', 'expirado', name='conveniostatus'), nullable=False))
        batch_op.add_column(sa.Column('criado_em', sa.TIMESTAMP(), nullable=False))
        batch_op.add_column(sa.Column('atualizado_em', sa.TIMESTAMP(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('convenio', schema=None) as batch_op:
        batch_op.drop_column('atualizado_em')
        batch_op.drop_column('criado_em')
        batch_op.drop_column('status')
        batch_op.drop_column('caminho_arquivo_pdf')
        batch_op.drop_column('observacoes')
        batch_op.drop_column('data_assinatura')
        batch_op.drop_column('diretor_responsavel')
        batch_op.drop_column('telefone_responsavel')
        batch_op.drop_column('email_responsavel')
        batch_op.drop_column('cargo_responsavel')
        batch_op.drop_column('responsavel_legal')
        batch_op.drop_column('qtd_sindicalizados')
        batch_op.drop_column('qtd_associados')
        batch_op.drop_column('qtd_funcionarios')
        batch_op.drop_column('area_atuacao')
        batch_op.drop_column('estado')
        batch_op.drop_column('nome_fantasia')
        batch_op.drop_column('cnpj')

    # ### end Alembic commands ###
