"""Adicionar coluna data_validade

Revision ID: b75b5fb40981
Revises: 5a9b42dc731b
Create Date: 2026-03-12 21:06:41.891495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b75b5fb40981'
down_revision = '5a9b42dc731b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('convenio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_validade', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Enum('ativo', 'rescindido', 'expirado', name='conveniostatus'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('convenio', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('data_validade')

    # ### end Alembic commands ###
