"""Adiciona campo de email do diretor

Revision ID: cda769ccc980
Revises: e5f96e280571
Create Date: 2025-09-24 13:18:36.417839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda769ccc980'
down_revision = 'e5f96e280571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('convenio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diretor_responsavel_email', sa.String(length=255), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    with op.batch_alter_table('convenio', schema=None) as batch_op:
        batch_op.drop_column('diretor_responsavel_email')

    # ### end Alembic commands ###
