"""Aumenta o tamanho do campo password_hash

Revision ID: df104d5b435a
Revises: 
Create Date: 2025-09-19 16:19:16.841231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df104d5b435a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convenio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome_conveniada', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=255), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=255), nullable=False),
    sa.Column('cidade', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=255), nullable=False),
    sa.Column('area_atuacao', sa.String(length=255), nullable=False),
    sa.Column('qtd_funcionarios', sa.Integer(), nullable=False),
    sa.Column('qtd_associados', sa.Integer(), nullable=False),
    sa.Column('qtd_sindicalizados', sa.Integer(), nullable=False),
    sa.Column('responsavel_legal', sa.String(length=255), nullable=False),
    sa.Column('cargo_responsavel', sa.String(length=255), nullable=False),
    sa.Column('email_responsavel', sa.String(length=255), nullable=False),
    sa.Column('telefone_responsavel', sa.String(length=255), nullable=False),
    sa.Column('unidade_uniesp', sa.String(length=255), nullable=False),
    sa.Column('diretor_responsavel', sa.String(length=255), nullable=False),
    sa.Column('data_assinatura', sa.Date(), nullable=False),
    sa.Column('observacoes', sa.TEXT(), nullable=True),
    sa.Column('caminho_arquivo_pdf', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('ativo', 'rescindido', 'expirado', name='conveniostatus'), nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(), nullable=False),
    sa.Column('atualizado_em', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('convenio')
    # ### end Alembic commands ###
